{
	"ActionResult": {
		"_Name": "sync"
	},
	"DefiningRequests": [
		{
			"Name": "Products",
			"Query": "Products"
		},
		{
			"Name": "SalesOrderHeaders",
			"Query": "SalesOrderHeaders"
		},
		{
			"Name": "SalesOrderItems",
			"Query": "SalesOrderItems"
		}
	],
	"OnFailure": "/RobSampleApp1/Actions/Service/SyncFailureMessage.action",
	"Service": "/RobSampleApp1/Services/SampleServiceV2.service",
	"_Type": "Action.Type.OfflineOData.Download"
}