{
	"ActionResult": {
		"_Name": "init"
	},
	"ActivityIndicatorText": "Downloading...",
	"DefiningRequests": [
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "Customers",
			"Query": "Customers"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "Products",
			"Query": "Products"
		}
	],
	"OnFailure": "/RobSampleApp1/Actions/Service/InitializeOfflineFailureMessage.action",
	"OnSuccess": "/RobSampleApp1/Actions/LogSetState.action",
	"Service": "/RobSampleApp1/Services/SampleServiceV2.service",
	"ShowActivityIndicator": true,
	"_Type": "Action.Type.OfflineOData.Initialize"
}